import { useCallback, useEffect, useRef, useState } from "react";
import { Modal } from "../../components/Modal.jsx";
import { IconRefresh } from "../../components/Icons.jsx";
import { IncomingBatchModal } from "../../features/review/IncomingBatchModal.jsx";
import { api } from "../../lib/api.js";

function useCountdown(expiresAt) {
  const [left, setLeft] = useState(null);

  useEffect(() => {
    if (!expiresAt) return;
    const target = new Date(expiresAt).getTime();
    const tick = () => setLeft(Math.max(0, Math.round((target - Date.now()) / 1000)));
    tick();
    const timer = setInterval(tick, 1000);
    return () => clearInterval(timer);
  }, [expiresAt]);

  return left;
}

/* The QR carries the server address and a signed, expiring session token, so a
   phone that scans it is already bound to this project — it never has to pick
   one. The session is minted on open; "New code" mints another.

   Scanned batches land hidden — awaiting_scan_decision — without
   auto-extracting (see batch_upload in Backend/main.py). Nothing about them
   is visible anywhere in the console, Documents included, until this modal's
   poll finds them and the office picks Process (read them now) or Draft
   (file them away unread) — closing without deciding just leaves that batch
   invisible; reopening this modal mints a new session and won't offer it
   again. handledIds is local-only, to stop an already-decided batch from
   reappearing between polls while its still-PENDING status catches up. */
export function ScanModal({ project, onClose, onProcess, onDraft }) {
  const [session, setSession] = useState(null);
  const [err, setErr] = useState("");
  const [busy, setBusy] = useState(false);
  const [incoming, setIncoming] = useState([]);
  const handledIds = useRef(new Set());
  const left = useCountdown(session?.expires_at);

  const mint = useCallback(async () => {
    setBusy(true);
    setErr("");
    handledIds.current = new Set();
    setIncoming([]);
    try {
      setSession(await api.createSession(project.id));
    } catch (e) {
      setErr(`Could not issue a code — ${e.message}`);
    } finally {
      setBusy(false);
    }
  }, [project.id]);

  useEffect(() => { mint(); }, [mint]);

  useEffect(() => {
    const sessionId = session?.session_id;
    if (!sessionId) return;
    let cancelled = false;
    let timer = null;

    const poll = async () => {
      try {
        const docs = await api.listDocuments({ session_id: sessionId, awaiting_decision: true });
        if (!cancelled) setIncoming(docs.filter((d) => !handledIds.current.has(d.document_id)));
      } catch {
        // transient — the next tick tries again
      }
      if (!cancelled) timer = setTimeout(poll, 3000);
    };

    poll();
    return () => { cancelled = true; if (timer) clearTimeout(timer); };
  }, [session?.session_id]);

  // IncomingBatchModal already confirmed the batch server-side (clearing
  // awaiting_scan_decision) by the time either callback fires — ids only
  // join handledIds once that's succeeded, so a failed request leaves the
  // prompt in place to retry rather than silently dropping the batch.
  const markHandled = (ids) => {
    ids.forEach((id) => handledIds.current.add(id));
    setIncoming([]);
  };

  const expired = left === 0;
  const clock =
    left == null
      ? "—"
      : `${String(Math.floor(left / 60)).padStart(2, "0")}:${String(left % 60).padStart(2, "0")}`;

  if (incoming.length > 0) {
    return (
      <IncomingBatchModal
        documents={incoming}
        onClose={onClose}
        onProcess={(ids) => { markHandled(ids); onProcess?.(ids); }}
        onDraft={(ids) => { markHandled(ids); onDraft?.(ids); }}
      />
    );
  }

  return (
    <Modal
      title="Scan with phone"
      subtitle={`${project.code} — ${project.name}`}
      onClose={onClose}
      footer={
        <>
          <div className="spacer" />
          <button className="btn btn-out" onClick={onClose}>Close</button>
          <button className="btn btn-ink" onClick={mint} disabled={busy}>
            <IconRefresh width={16} height={16} />
            New code
          </button>
        </>
      }
    >
      {err ? <div className="banner banner-err">{err}</div> : null}

      <div className="qr-frame">
        {/* SVG generated by our own backend from the session payload. The XML
            prolog it ships with is invalid inside an HTML document, so it goes
            before the markup is inlined. */}
        {session?.qr_svg
          ? <div dangerouslySetInnerHTML={{ __html: session.qr_svg.replace(/^\s*<\?xml[^>]*\?>\s*/, "") }} />
          : <div className="empty">{busy ? "Issuing a code…" : "No code was issued."}</div>}
      </div>

      <ol className="steps">
        <li>Open the scanner app on the site phone.</li>
        <li>Point it at this code — it carries the server, the session and the project.</li>
        <li>Photograph each document; pages upload as you go.</li>
      </ol>

      <div className="kv">
        <div><span>Project</span><span>{project.code}</span></div>
        <div><span>Session</span><span>{session?.session_id?.slice(0, 8) ?? "—"}</span></div>
        <div>
          <span>Expires in</span>
          <span className={`countdown ${expired ? "expired" : left != null && left < 120 ? "warn" : ""}`}>
            {expired ? "expired — tap New code" : clock}
          </span>
        </div>
      </div>
    </Modal>
  );
}
